version: "3.3"
services:
  spark-master:
    image: emragins/spark
    container_name: spark-master
    hostname: spark-master
    command: >
      /bin/sh -c '
      /spark/sbin/start-master.sh
      && tail -f /spark/logs/*'
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    ports:
      - 8090:8080
      - 7077:7077
    networks:
      - spark-network
  spark-worker:
    image: emragins/spark
    depends_on:
      - spark-master
    command: >
      /bin/sh -c '
      /spark/sbin/start-worker.sh $$SPARK_MASTER
      && tail -f /spark/logs/*'
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8080
    ports:
      - 8080
    networks:
      - spark-network
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default